package ca.sait.amt.restapplication.entity;
// Generated Jan. 19, 2023, 2:55:38 p.m. by Hibernate Tools 4.3.6.Final

import static jakarta.persistence.GenerationType.IDENTITY;

import com.fasterxml.jackson.annotation.JsonBackReference;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;

/**
 * Project generated by hbm2java
 */
@Entity
@Table(name = "billing_address", catalog = "amt")
public class BillingAddress implements java.io.Serializable {

	private int billingAddressId;
	private String firstLineAddress;
	private String secondLineAddress;
	private String postalCode;
	private String city;
	private String province;
	private DepositForm depositForm;

	public BillingAddress() {
	}
	
	public BillingAddress(int billingAddressId, String firstLineAddress, String secondLineAddress, String postalCode,
			String city, String province, DepositForm depositForm) {
		super();
		this.billingAddressId = billingAddressId;
		this.firstLineAddress = firstLineAddress;
		this.secondLineAddress = secondLineAddress;
		this.postalCode = postalCode;
		this.city = city;
		this.province = province;
		this.depositForm = depositForm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "billingAddressId", unique = true, nullable = false)
	public Integer getBillingAddressId() {
		return this.billingAddressId;
	}

	public void setBillingAddressId(Integer billingAddressId) {
		this.billingAddressId = billingAddressId;
	}

	@OneToOne(fetch = FetchType.EAGER, cascade=CascadeType.ALL)
	@JsonBackReference
	@JoinColumn(name = "deposit_form_id")
	public DepositForm getDepositForm() {
		return this.depositForm;
	}

	public void setDepositForm(DepositForm depositForm) {
		this.depositForm = depositForm;
	}

	@Column(name = "first_line_address")
	public String getFirstLineAddress() {
		return firstLineAddress;
	}

	public void setFirstLineAddress(String firstLineAddress) {
		this.firstLineAddress = firstLineAddress;
	}

	@Column(name = "second_line_address")
	public String getSecondLineAddress() {
		return secondLineAddress;
	}

	public void setSecondLineAddress(String secondLineAddress) {
		this.secondLineAddress = secondLineAddress;
	}

	@Column(name = "postal_code")
	public String getPostalCode() {
		return postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	@Column(name = "city")
	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "province")
	public String getProvince() {
		return province;
	}

	public void setProvince(String province) {
		this.province = province;
	}
	
	@Transient
	public int getDepositFormId() {
		return depositForm.getInvoiceId();
	}
}
