package ca.sait.amt.restapplication.entity;
// Generated Jan. 19, 2023, 2:55:38 p.m. by Hibernate Tools 4.3.6.Final

import static jakarta.persistence.GenerationType.IDENTITY;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;

/**
 * ClientContact generated by hbm2java
 */
@Entity
@Table(name = "client_contact", catalog = "amt")
public class ClientContact implements java.io.Serializable {

	private Integer clientContactId;
	private String personalContactNumber;
	private String personalEmail;
	private String businessEmail;
	private Integer clientId;
	private Client client;

	public ClientContact() {
	}

	public ClientContact(String personalContactNumber, String personalEmail, String businessEmail, Integer clientId,
			Client client) {
		this.personalContactNumber = personalContactNumber;
		this.personalEmail = personalEmail;
		this.businessEmail = businessEmail;
		this.clientId = clientId;
		this.client = client;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "client_contact_id", unique = true, nullable = false)
	public Integer getClientContactId() {
		return this.clientContactId;
	}

	public void setClientContactId(Integer clientContactId) {
		this.clientContactId = clientContactId;
	}

	@Column(name = "personal_contact_number")
	public String getPersonalContactNumber() {
		return this.personalContactNumber;
	}

	public void setPersonalContactNumber(String personalContactNumber) {
		this.personalContactNumber = personalContactNumber;
	}

	@Column(name = "personal_email", length = 45)
	public String getPersonalEmail() {
		return this.personalEmail;
	}

	public void setPersonalEmail(String personalEmail) {
		this.personalEmail = personalEmail;
	}

	@Column(name = "business_email", length = 45)
	public String getBusinessEmail() {
		return this.businessEmail;
	}

	public void setBusinessEmail(String businessEmail) {
		this.businessEmail = businessEmail;
	}

	@Column(name = "client_id")
	public Integer getClientId() {
		return this.clientId;
	}

	public void setClientId(Integer clientId) {
		this.clientId = clientId;
	}

	
	@OneToOne(fetch = FetchType.LAZY, mappedBy = "clientContact", cascade=CascadeType.ALL)
	@JsonBackReference
	@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
	public Client getClients() {
		return this.client;
	}

	public void setClients(Client client) {
		this.client = client;
	}

}
