package ca.sait.amt.restapplication.entity;
// Generated Jan. 19, 2023, 2:55:38 p.m. by Hibernate Tools 4.3.6.Final

import static jakarta.persistence.GenerationType.IDENTITY;

import org.springframework.boot.context.properties.ConfigurationProperties;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;

/**
 * Image generated by hbm2java
 */

@ConfigurationProperties(prefix = "file")
@Entity
@Table(name = "image", catalog = "amt")
public class Image implements java.io.Serializable {

	private Integer imageId;
	private Project project;
	private String imageType;
	private String imageName;
	private String imageUrl;
	private String imageFormat;
	private long imageSize;

	public Image() {
	}

	public Image(Project project, String imageType, String imageName, String imageUrl, String imageFormat,
			long imageSize) {
		super();
		this.project = project;
		this.imageType = imageType;
		this.imageName = imageName;
		this.imageUrl = imageUrl;
		this.imageFormat = imageFormat;
		this.imageSize = imageSize;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "image_id", unique = true, nullable = false)
	public Integer getImageId() {
		return this.imageId;
	}

	public void setImageId(Integer imageId) {
		this.imageId = imageId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_id")
	@JsonBackReference
	@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@Column(name = "image_type", nullable = false, length = 30)
	public String getImageType() {
		return this.imageType;
	}

	public void setImageType(String imageType) {
		this.imageType = imageType;
	}

	@Column(name = "image_size")
	public long getImageSize() {
		return this.imageSize;
	}

	public void setImageSize(long imageSize) {
		this.imageSize = imageSize;
	}

	@Column(name = "image_name", nullable = false, length = 36)
	public String getImageName() {
		return this.imageName;
	}

	public void setImageName(String imageName) {
		this.imageName = imageName;
	}

	@Column(name = "image_format", nullable = false, length = 20)
	public String getImageFormat() {
		return imageFormat;
	}

	public void setImageFormat(String imageFormat) {
		this.imageFormat = imageFormat;
	}

	@Column(name = "image_url", nullable = false, length = 50)
	public String getImageUrl() {
		return this.imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	@Transient
	public Integer getProjectId() {
		return project.getProjectId();
	}
}
