package ca.sait.amt.restapplication.entity;
// Generated Jan. 19, 2023, 2:55:38 p.m. by Hibernate Tools 4.3.6.Final

import static jakarta.persistence.GenerationType.IDENTITY;

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonManagedReference;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Invoice generated by hbm2java
 */
@Entity
@Table(name = "invoice", catalog = "amt")
public class Invoice implements java.io.Serializable {

	private Integer invoiceId;
	private Project project;
	private Double invoiceTotalPrice;
	private Date dateCreated;
	private Set<InvoiceItem> invoiceItems = new HashSet<InvoiceItem>(0);

	public Invoice() {
	}

	public Invoice(Project project, int invoiceNumber, String documentName, Date dateCreated, Double invoiceTotalPrice,
			Set<InvoiceItem> invoiceItems) {
		this.project = project;
		this.invoiceTotalPrice = invoiceTotalPrice;
		this.invoiceItems = invoiceItems;
		this.dateCreated = dateCreated;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "invoice_id", unique = true, nullable = false)
	public Integer getInvoiceId() {
		return this.invoiceId;
	}

	public void setInvoiceId(Integer invoiceId) {
		this.invoiceId = invoiceId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JsonBackReference
	@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
	@JoinColumn(name = "project_id")
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@Column(name = "invoice_total_price", precision = 8)
	public Double getInvoiceTotalPrice() {
		return this.invoiceTotalPrice;
	}

	public void setInvoiceTotalPrice(Double invoiceTotalPrice) {
		this.invoiceTotalPrice = invoiceTotalPrice;
	}
	
	@Column(name = "date_created")
	public Date getDateCreated() {
		return dateCreated;
	}
	
	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "invoice")
	@JsonManagedReference
	public Set<InvoiceItem> getInvoiceItems() {
		return this.invoiceItems;
	}

	public void setInvoiceItems(Set<InvoiceItem> invoiceItems) {
		this.invoiceItems = invoiceItems;
	}

}
