package ca.sait.amt.restapplication.entity;
// Generated Jan. 19, 2023, 2:55:38 p.m. by Hibernate Tools 4.3.6.Final

import static jakarta.persistence.GenerationType.IDENTITY;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;

/**
 * Project generated by hbm2java
 */
@Entity
@Table(name = "project_address", catalog = "amt")
public class ProjectAddress implements java.io.Serializable {

	private int projectAddressId;
	private int streetNumber;
	private String street;
	private String postalCode;
	private Project project;
	
	public ProjectAddress() {
	}	

	public ProjectAddress(int projectAddressId, int streetNumber, String street, String postalCode, Project project) {
		this.streetNumber = streetNumber;
		this.street = street;
		this.postalCode = postalCode;
		this.project = project;
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "projectAddressId", unique = true, nullable = false)
	public Integer getProjectAddressId() {
		return this.projectAddressId;
	}

	public void setProjectAddressId(Integer projectAddressId) {
		this.projectAddressId = projectAddressId;
	}

	@OneToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "project")
	public Project getProject() {
		return this.project;
	}
	
	public void setProject(Project project) {
		this.project = project;
	}

	@Column(name = "street_number")
	public int getStreetNumber() {
		return streetNumber;
	}

	public void setStreetNumber(int streetNumber) {
		this.streetNumber = streetNumber;
	}

	@Column(name = "street")
	public String getStreet() {
		return street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	@Column(name = "postal_code")
	public String getPostalCode() {
		return postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}
	
	
}
