package ca.sait.amt.restapplication.entity;
// Generated Jan. 19, 2023, 2:55:38 p.m. by Hibernate Tools 4.3.6.Final

import static jakarta.persistence.GenerationType.IDENTITY;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;

/**
 * Project generated by hbm2java
 */
@Entity
@Table(name = "project_address", catalog = "amt")
public class ProjectAddress implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8692709818176693383L;
	private int projectAddressId;
	private String firstLineAddress;
	private String secondLineAddress;
	private String postalCode;
	private String city;
	private String province;
	private Project project;

	public ProjectAddress() {
	}
	
	public ProjectAddress(int projectAddressId, String firstLineAddress, String secondLineAddress, String postalCode,
			String city, String province, Project project) {
		super();
		this.projectAddressId = projectAddressId;
		this.firstLineAddress = firstLineAddress;
		this.secondLineAddress = secondLineAddress;
		this.postalCode = postalCode;
		this.city = city;
		this.province = province;
		this.project = project;
	}



	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "projectAddressId", unique = true, nullable = false)
	public Integer getProjectAddressId() {
		return this.projectAddressId;
	}

	public void setProjectAddressId(Integer projectAddressId) {
		this.projectAddressId = projectAddressId;
	}

	@OneToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "project")
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@Column(name = "first_line_address")
	public String getFirstLineAddress() {
		return firstLineAddress;
	}

	public void setFirstLineAddress(String firstLineAddress) {
		this.firstLineAddress = firstLineAddress;
	}

	@Column(name = "second_line_address")
	public String getSecondLineAddress() {
		return secondLineAddress;
	}

	public void setSecondLineAddress(String secondLineAddress) {
		this.secondLineAddress = secondLineAddress;
	}

	@Column(name = "postal_code")
	public String getPostalCode() {
		return postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	@Column(name = "city")
	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "province")
	public String getProvince() {
		return province;
	}

	public void setProvince(String province) {
		this.province = province;
	}
}
