package ca.sait.amt.restapplication.entity;
// Generated Jan. 19, 2023, 2:55:38 p.m. by Hibernate Tools 4.3.6.Final

import static jakarta.persistence.GenerationType.IDENTITY;

import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Quote generated by hbm2java
 */
@Entity
@Table(name = "quote", catalog = "amt")
public class Quote implements java.io.Serializable {

	private Integer quoteId;
	private Project project;
	private double quotePrice;
	private Date quoteDate;

	public Quote() {
	}

	public Quote(double quotePrice) {
		this.quotePrice = quotePrice;
	}

	public Quote(Project project, double quotePrice, Date quoteDate) {
		this.project = project;
		this.quotePrice = quotePrice;
		this.quoteDate = quoteDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "quote_id", unique = true, nullable = false)
	public Integer getQuoteId() {
		return this.quoteId;
	}

	public void setQuoteId(Integer quoteId) {
		this.quoteId = quoteId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_id")
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@Column(name = "quote_price", nullable = false, precision = 8)
	public double getQuotePrice() {
		return this.quotePrice;
	}

	public void setQuotePrice(double quotePrice) {
		this.quotePrice = quotePrice;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "quote_date", length = 19)
	public Date getQuoteDate() {
		return this.quoteDate;
	}

	public void setQuoteDate(Date quoteDate) {
		this.quoteDate = quoteDate;
	}

}
