package ca.sait.amt.restappilcation.entity;
// Generated Jan. 19, 2023, 2:55:38 p.m. by Hibernate Tools 4.3.6.Final

import static jakarta.persistence.GenerationType.IDENTITY;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * DepositForm generated by hbm2java
 */
@Entity
@Table(name = "deposit_form", catalog = "amt")
public class DepositForm implements java.io.Serializable {

	private Integer depositFormId;
	private Project project;
	private int depositFormStatus;
	private double depositAmount;

	public DepositForm() {
	}

	public DepositForm(int depositFormStatus, double depositAmount) {
		this.depositFormStatus = depositFormStatus;
		this.depositAmount = depositAmount;
	}

	public DepositForm(Project project, int depositFormStatus, double depositAmount) {
		this.project = project;
		this.depositFormStatus = depositFormStatus;
		this.depositAmount = depositAmount;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "deposit_form_id", unique = true, nullable = false)
	public Integer getDepositFormId() {
		return this.depositFormId;
	}

	public void setDepositFormId(Integer depositFormId) {
		this.depositFormId = depositFormId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_id")
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@Column(name = "deposit_form_status", nullable = false)
	public int getDepositFormStatus() {
		return this.depositFormStatus;
	}

	public void setDepositFormStatus(int depositFormStatus) {
		this.depositFormStatus = depositFormStatus;
	}

	@Column(name = "deposit_amount", nullable = false, precision = 8)
	public double getDepositAmount() {
		return this.depositAmount;
	}

	public void setDepositAmount(double depositAmount) {
		this.depositAmount = depositAmount;
	}

}
