package ca.sait.amt.restappilcation.entity;
// Generated Jan. 19, 2023, 2:55:38 p.m. by Hibernate Tools 4.3.6.Final

import static jakarta.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Invoice generated by hbm2java
 */
@Entity
@Table(name = "invoice", catalog = "amt")
public class Invoice implements java.io.Serializable {

	private Integer invoiceId;
	private Project project;
	private int invoiceNumber;
	private String documentName;
	private Double invoiceTotalPrice;
	private Set<InvoiceItem> invoiceItems = new HashSet<InvoiceItem>(0);

	public Invoice() {
	}

	public Invoice(int invoiceNumber, String documentName) {
		this.invoiceNumber = invoiceNumber;
		this.documentName = documentName;
	}

	public Invoice(Project project, int invoiceNumber, String documentName, Double invoiceTotalPrice,
			Set<InvoiceItem> invoiceItems) {
		this.project = project;
		this.invoiceNumber = invoiceNumber;
		this.documentName = documentName;
		this.invoiceTotalPrice = invoiceTotalPrice;
		this.invoiceItems = invoiceItems;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "invoice_id", unique = true, nullable = false)
	public Integer getInvoiceId() {
		return this.invoiceId;
	}

	public void setInvoiceId(Integer invoiceId) {
		this.invoiceId = invoiceId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_id")
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@Column(name = "invoice_number", nullable = false)
	public int getInvoiceNumber() {
		return this.invoiceNumber;
	}

	public void setInvoiceNumber(int invoiceNumber) {
		this.invoiceNumber = invoiceNumber;
	}

	@Column(name = "document_name", nullable = false, length = 12)
	public String getDocumentName() {
		return this.documentName;
	}

	public void setDocumentName(String documentName) {
		this.documentName = documentName;
	}

	@Column(name = "invoice_total_price", precision = 8)
	public Double getInvoiceTotalPrice() {
		return this.invoiceTotalPrice;
	}

	public void setInvoiceTotalPrice(Double invoiceTotalPrice) {
		this.invoiceTotalPrice = invoiceTotalPrice;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "invoice")
	public Set<InvoiceItem> getInvoiceItems() {
		return this.invoiceItems;
	}

	public void setInvoiceItems(Set<InvoiceItem> invoiceItems) {
		this.invoiceItems = invoiceItems;
	}

}
