package ca.sait.amt.restappilcation.entity;
// Generated Jan. 19, 2023, 2:55:38 p.m. by Hibernate Tools 4.3.6.Final

import static jakarta.persistence.GenerationType.IDENTITY;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * InvoiceItem generated by hbm2java
 */
@Entity
@Table(name = "invoice_item", catalog = "amt")
public class InvoiceItem implements java.io.Serializable {

	private Integer invoiceItemId;
	private Invoice invoice;
	private String invoiceItemName;
	private double invoiceItemPrice;

	public InvoiceItem() {
	}

	public InvoiceItem(String invoiceItemName, double invoiceItemPrice) {
		this.invoiceItemName = invoiceItemName;
		this.invoiceItemPrice = invoiceItemPrice;
	}

	public InvoiceItem(Invoice invoice, String invoiceItemName, double invoiceItemPrice) {
		this.invoice = invoice;
		this.invoiceItemName = invoiceItemName;
		this.invoiceItemPrice = invoiceItemPrice;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "invoice_item_id", unique = true, nullable = false)
	public Integer getInvoiceItemId() {
		return this.invoiceItemId;
	}

	public void setInvoiceItemId(Integer invoiceItemId) {
		this.invoiceItemId = invoiceItemId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "invoice_id")
	public Invoice getInvoice() {
		return this.invoice;
	}

	public void setInvoice(Invoice invoice) {
		this.invoice = invoice;
	}

	@Column(name = "invoice_item_name", nullable = false, length = 12)
	public String getInvoiceItemName() {
		return this.invoiceItemName;
	}

	public void setInvoiceItemName(String invoiceItemName) {
		this.invoiceItemName = invoiceItemName;
	}

	@Column(name = "invoice_item_price", nullable = false, precision = 8)
	public double getInvoiceItemPrice() {
		return this.invoiceItemPrice;
	}

	public void setInvoiceItemPrice(double invoiceItemPrice) {
		this.invoiceItemPrice = invoiceItemPrice;
	}

}
