package ca.sait.amt.restappilcation.entity;
// Generated Jan. 19, 2023, 2:55:38 p.m. by Hibernate Tools 4.3.6.Final

import static jakarta.persistence.GenerationType.IDENTITY;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * PurchaseOrderItem generated by hbm2java
 */
@Entity
@Table(name = "purchase_order_item", catalog = "amt")
public class PurchaseOrderItem implements java.io.Serializable {

	private Integer purchaseOrderItemId;
	private PurchaseOrder purchaseOrder;
	private String purchaseOrderItemName;
	private double purchaseOrderItemPrice;

	public PurchaseOrderItem() {
	}

	public PurchaseOrderItem(String purchaseOrderItemName, double purchaseOrderItemPrice) {
		this.purchaseOrderItemName = purchaseOrderItemName;
		this.purchaseOrderItemPrice = purchaseOrderItemPrice;
	}

	public PurchaseOrderItem(PurchaseOrder purchaseOrder, String purchaseOrderItemName, double purchaseOrderItemPrice) {
		this.purchaseOrder = purchaseOrder;
		this.purchaseOrderItemName = purchaseOrderItemName;
		this.purchaseOrderItemPrice = purchaseOrderItemPrice;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "purchase_order_item_id", unique = true, nullable = false)
	public Integer getPurchaseOrderItemId() {
		return this.purchaseOrderItemId;
	}

	public void setPurchaseOrderItemId(Integer purchaseOrderItemId) {
		this.purchaseOrderItemId = purchaseOrderItemId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "purchase_order_id")
	public PurchaseOrder getPurchaseOrder() {
		return this.purchaseOrder;
	}

	public void setPurchaseOrder(PurchaseOrder purchaseOrder) {
		this.purchaseOrder = purchaseOrder;
	}

	@Column(name = "purchase_order_item_name", nullable = false, length = 12)
	public String getPurchaseOrderItemName() {
		return this.purchaseOrderItemName;
	}

	public void setPurchaseOrderItemName(String purchaseOrderItemName) {
		this.purchaseOrderItemName = purchaseOrderItemName;
	}

	@Column(name = "purchase_order_item_price", nullable = false, precision = 8)
	public double getPurchaseOrderItemPrice() {
		return this.purchaseOrderItemPrice;
	}

	public void setPurchaseOrderItemPrice(double purchaseOrderItemPrice) {
		this.purchaseOrderItemPrice = purchaseOrderItemPrice;
	}

}
